version: '3'
services:
  app:
    container_name: app-backend
    restart: always
    build: .
    volumes:
      - .:/usr/src/app-backend
    working_dir: /usr/src/app-backend
    ports:
      - '80:5000'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/meow

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
